#!/bin/bash

GIT_WD=$(git rev-parse --show-toplevel)
KEY=$(find $GIT_WD -maxdepth 1 -type l -name ".git_key_pointer")

if [[ $KEY ]]; then
  ssh -i $KEY -F /dev/null -o "IdentitiesOnly yes" $@
else
  ssh $@
fi

