#!/bin/bash

CACHE_DIR="/home/tomk/cachestuff"
CACHE_FILE_NAME="node_list"
GET_DATA_COMMAND="knife node list"

STASH_DIR="${CACHE_DIR}/${CACHE_FILE_NAME}.d"
SYM_LINK="${CACHE_DIR}/${CACHE_FILE_NAME}"
UPDATED_FILE_TARGET="${CACHE_FILE_NAME}_$(date +%F-%T)"

exiterr() {
  echo "$1" >&2 && exit 2;
}

if [[ ! -d $STASH_DIR ]]; then
  mkdir $STASH_DIR || exiterr "cannot create stash dir at ${STASH_DIR}";
fi

cd ${STASH_DIR}
bash -c "${GET_DATA_COMMAND}" > ${UPDATED_FILE_TARGET}
cd ..
if [[ -e ${SYM_LINK} ]]; then
  if [[ ! -L ${SYM_LINK} ]]; then
    exiterr "${SYM_LINK} exists but is not a symbolic link";
  else
    rm ${SYM_LINK}
  fi
fi

ln -s ${CACHE_FILE_NAME}.d/${UPDATED_FILE_TARGET} ${CACHE_FILE_NAME}
